### ISSUE TITLE
Test VC doesn't include proper context

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-ed25519signature2020-test-suite#50]
The only context included in the [test vc](https://github.com/w3c/vc-di-ed25519signature2020-test-suite/blob/8a18d629d472bb35f4d0f9f5b9709f206f2cb8f5/tests/vc-generator/testVc.js#L2) is the credentials context. This context unfortunately doesn't have properties for this suite. I think the `'https://w3id.org/security/suites/ed25519-2020/v1'` context is required

**Comment by brianorwhatever** [comment]
This issue is also happening in data-integrity-test-suite-assertion test VC so it feels like I'm doing something wrong. What am I missing here @aljones15?

**Comment by aljones15** [comment]
@brianorwhatever ok so checked

https://www.w3.org/TR/vc-di-eddsa/#ed25519signature2020-0

ed25519 2020 is part of the data integrity suites, but it is a little bit of an exception:

> Ed25519Signature2020 is an earlier version of a cryptographic suite for the usage of the EdDSA algorithm and Curve25519. While it has been used in production systems, new implementations should use [edssa-2022](https://www.w3.org/TR/vc-di-eddsa/#eddsa-rdfc-2022) instead. It has been kept in this specification to provide a stable reference.

As part of the di suites context inject should occur:

https://www.w3.org/TR/vc-data-integrity/#context-injection

**Comment by brianorwhatever** [comment]
Ok, cool. That text clears things up. I'll have to add this into implementation then
